[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_APP_URL = "https://sage-tarsier-045b32.netlify.app"