[phases.setup]
nixPkgs = ["python310", "python310Packages.pip"]

[phases.install]
cmds = [
  "python3 --version",
  "cd Backend && python3 -m pip install --upgrade pip",
  "cd Backend && python3 -m pip install -r requirements.txt"
]

[phases.build]
cmds = ["cd Backend && echo 'Build completed'"]

[start]
cmd = "cd Backend && python3 -m uvicorn app.main:app --host 0.0.0.0 --port $PORT --timeout-keep-alive=300" 