[build]
builder = "nixpacks"
nixpacksConfigPath = "nixpacks.toml"
buildCommand = "chmod +x custom_start.sh && pip install -r Backend/requirements.txt"

[deploy]
startCommand = "./custom_start.sh"
healthcheckPath = "/"
healthcheckTimeout = 300

[nixpacks]
provider = "python" 